USE edi3;

-- DROP TABLE IF EXISTS DOC_MEMORANDUM;
-- DROP TABLE IF EXISTS DOC_MESSAGE;
-- DROP TABLE IF EXISTS BP_EXECUTOR_TASK_FOLDER_STRUCTURE;
-- DROP TABLE IF EXISTS BP_SEQUENCE;
-- DROP TABLE IF EXISTS hibernate_sequence;
-- DROP TABLE IF EXISTS CAT_UPLOADED_FILE;
--
-- DROP TABLE IF EXISTS IR_USER_ACCESS_RIGHT;
-- DROP TABLE IF EXISTS BP_EXECUTOR_TASK;
-- DROP TABLE IF EXISTS BP_BUSINESS_PROCESS;
-- DROP TABLE IF EXISTS NUMERATION;
-- DROP TABLE IF EXISTS DOC_ABSTRACT_DOCUMENT_EDI;
DROP TABLE IF EXISTS CAT_USER;
-- DROP TABLE IF EXISTS CAT_PROPOSAL_TEMPLATE;
DROP TABLE IF EXISTS CAT_POSITION;
DROP TABLE IF EXISTS CAT_DEPARTMENT;

-- DROP TABLE IF EXISTS CAT_CONTRACTOR;
-- DROP TABLE IF EXISTS CAT_COST_ITEM;
-- DROP TABLE IF EXISTS CAT_CURRENCY;
-- DROP TABLE IF EXISTS CAT_LEGAL_ORGANIZATION;
-- DROP TABLE IF EXISTS CAT_PLANNING_PERIOD;

DROP TABLE IF EXISTS HIBERNATE_SEQUENCE;